name: Muscle CI

on:
  push:
    paths:
      - 'nue/muscle/**'
  pull_request:
    paths:
      - 'nue/muscle/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nue/muscle

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (ffmpeg)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Set up Cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
